-- USE MDMW_DB
DROP TABLE IF EXISTS APP_USER;

CREATE TABLE APP_USER (
	id INT IDENTITY(1, 1) CONSTRAINT PK_APP_USER_id PRIMARY KEY,
	username VARCHAR(20) NOT NULL,
	mail VARCHAR(30) NOT NULL,
	password VARCHAR(255) NOT NULL,
	isAdmin BIT
);

DROP TABLE IF EXISTS APP_GROUP;

CREATE TABLE APP_GROUP (
	id INT IDENTITY(1, 1) CONSTRAINT PK_APP_GROUP_id PRIMARY KEY,
	name VARCHAR(20) NOT NULL,
	id_owner INT NOT NULL CONSTRAINT FK_APP_GROUP_owner FOREIGN KEY (id_owner) REFERENCES APP_USER(id)
);

DROP TABLE IF EXISTS NOTEBOOK;

CREATE TABLE NOTEBOOK (
	id INT IDENTITY(1, 1) CONSTRAINT PK_NOTEBOOK_id PRIMARY KEY,
	title VARCHAR(20) NOT NULL,
	creationDate DATE NOT NULL,
	modificationDate DATE NOT NULL,,
	isActive BIT NOT NULL,
	link VARCHAR(50) NULL,
	id_group INT NULL CONSTRAINT FK_NOTEBOOK_app_group FOREIGN KEY (id_group) REFERENCES APP_GROUP(id)
);

DROP TABLE IF EXISTS NOTE;

CREATE TABLE NOTE (
	id INT IDENTITY(1, 1) CONSTRAINT PK_NOTE_id PRIMARY KEY,
	notebook INT NOT NULL CONSTRAINT FK_NOTE_notebook FOREIGN KEY (notebook) REFERENCES NOTEBOOK(id),
	content VARCHAR(3005) NOT NULL,
	previousNote INT NULL CONSTRAINT FK_NOTE_previousNote FOREIGN KEY (previousNote) REFERENCES NOTE(id) ON DELETE NO ACTION
);

